### ISSUE TITLE
Can anyone tell me what this means?

### ISSUE THREAD

**Issue by Boghengis** [dmarx/video-killed-the-radio-star#103]
I'm trying to compile some frames I don't want to lose
![Screenshot_20230126-182125](https://user-images.githubusercontent.com/123707488/214989173-140499e4-eca8-4a3e-baa2-2c440fe2fd48.png)

**Comment by dmarx** [comment]
if you have google drive mounted, you should be able to find those frames on your drive, and you should be able to reload the same frames by specifying the same project name you used to generate them. 

the error you are seeing here means the library "omegaconf" was not installed, which suggests to me that you skipped the setup cell. this is a little funny since you said you've already generated frames, which wouldn't be possible if the setup cell were skipped. I'm guessing this means you ran this cell on a different runtime (i.e. virtual machine) than the one you used to generate the images, which means if the notebook wasn't connected to google drive, you've already lost those generations already. if the notebook is still open in your browser, you might be able to download the images from the notebook directly by right clicking them, selecting 'open image in new tab', and saving from there. or something like that. otherwise, best you can do is probably to take screenshots and crop after wards.
