### ISSUE TITLE
dumb question: how do I upload an mp3? or point to it? 

### ISSUE THREAD

**Issue by sandimus** [dmarx/video-killed-the-radio-star#119]
I have the mp3 in my Google Drive and on my laptop, using the file path didnt' work

**Comment by dmarx** [comment]
The path to the file in google drive will need to start with something like `/content/drive/MyDrive/<the rest of the path here>`. The left bar of google colab has a folder icon: if you click on that, it'll open a file navigator. If you can navigate to your file in that window, right click on it and select "copy path" to get the full path to the file. otherwise, another thing you can try is to just drag the file over that file browser and then i think it'll be available at `/content/<your mp3 filename>`
