### ISSUE TITLE
['images_fpaths'] line 57 - can't assign to literal error

### ISSUE THREAD

**Issue by deeplearner5** [dmarx/video-killed-the-radio-star#14]
Hi
Running a colab copy at line 57 block 7, I get:

```
        ['images_fpaths'] = [
            save_frame(
                img,
                idx,
                root_path=Path('./frames') / proj_name,
                #name=proj_name, ## need to make sure each image gets a unique name
            ) for j, img in enumerate(rec['images'])
        ]
```

File ["<ipython-input-8-9988bfac5c16>"](https://localhost:8080/#), line 57
    ['images_fpaths'] = [
    ^
SyntaxError: can't assign to literal

Any ideas?
Thanks
Al/dl5

**Comment by dmarx** [comment]
should be fixed now if you open the latest version of the notebook. if you encounter this error again -- either because you want to use the notebook session you've already been working in, or made a copy of the notebook, or it's cached in your browse.... whatever nbd -- just add "rec" in front of that first line so it looks like this: `rec['images_fpaths'] = [`
